name: Deploy via SFTP

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure lftp is installed
        run: command -v lftp || (sudo apt-get update && sudo apt-get install -y lftp)

      - name: Deploy
        env:
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_USER: ${{ secrets.SFTP_USER }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
          SFTP_TARGET_PATH: ${{ secrets.SFTP_TARGET_PATH }}
        run: |
          lftp -e "
          set sftp:auto-confirm yes
          open -u ${SFTP_USER},${SFTP_PASSWORD} sftp://${SFTP_HOST}

          mirror --reverse \
            --ignore-time \
            --parallel=5 \
            --verbose=1 \
            --exclude-glob .git/ \
            --exclude-glob .github/ \
            --exclude-glob .gitignore \
            --exclude-glob README.md \
            ./ ${SFTP_TARGET_PATH}
          bye
          "
